language: node_js
node_js:
  - 'node'
env:
  global:
    - CXX=g++-4.8
    secure: HxcD79l+id6rYDUwJN94BnWTTzR9w+xqDmOQ/GToQnE4nLS4Vz7OEgrvNd+qulQaWkw7E5fPw935IKdymV7Ij7riCGx8TOBGq0R1u+x8n75mvNhzFQKDeVpKe2aXWPfurxOWWOTorptUnod0WXNrUdCTIbnmuA46oNF6O/VUE9dxmKZRcfKu3VgWdSarNZ1CGQN7KoF5qQYRgNVvJ+MQ+Myn0FNrRiR1uvbFR4bBonybawwjGwsG/wJsf2QmKzqffPXV9U5W9MOfNVmp06ktxCi2QQ1x8ZLXOlFA/RL8VhMTP94dk/j2FDJGwpfz0kKd7+DeZrqEx7k2daOjPbjR0mOdhFEpdbCJ54/SMzDs2w40Z51rk7YYBI0Akp8L/PmGMxLJzXOlNB3MKgBF5DdL7T4wTus3PJ2f1qBTXHkrPMWs0KQdpSU1MmrwUFx1XEGfIY5QMt87jaakl1htaGxsA721Mhe36tTjHc5y9x8g36plt1YX8ty6bVO8GewrFS+FH/oCDpNiG7tQHXL5MeGJqHWMAaGFJEntRmCXExfoVALIBaqSyoeOcJjaLw/GbLFx2uaMNpV+bj99dSTswXNBZuZ/aGEJYRoWkmaZqSYttESUaSreZb9yYrEJ3+uoi+5zl+9vmZ0cd2cC1ITafJdc8jLdZvSBC1LiY/ZmXaFTx/g=
  matrix:
    - TEST_DIR=client
    - TEST_DIR=server
before_install:
  - cd TEST_DIR
